# Create docker-compose.yml
version: '3.8'

services:
  zora-vm:
    build: .
    image: ghcr.io/plutomaster28/zora-vm:latest  # Updated to lowercase
    container_name: zora-vm-instance
    stdin_open: true
    tty: true
    volumes:
      # Persistent storage for user files
      - ./ZoraPerl-data:/home/zora/ZoraPerl
      # Optional: Mount additional directories
      - ./scripts:/home/zora/shared-scripts:ro
    environment:
      - TERM=xterm-256color
      - ZORA_VM_MODE=docker
    # Optional: expose ports if you add web interface later
    # ports:
    #   - "8080:8080"
    restart: unless-stopped

  # Optional: Add a development version with more tools
  zora-vm-dev:
    build: 
      context: .
      target: builder  # Use the builder stage with more tools
    image: ghcr.io/plutomaster28/zora-vm:dev  # Updated to lowercase
    container_name: zora-vm-dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
      - ./ZoraPerl-data:/home/zora/ZoraPerl
    working_dir: /workspace
    command: /bin/bash